- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Cog
  - Core
  - Fland
  #- Gate
  - Loop
  - Marathon
  - MetaStation
  - Oasis
  - Omega
  - Packed
  - Reach
  #- Train
  - Driller
  - Lighthouse
  - Elstation
